import { Metadata } from "next";
import { Inter } from "next/font/google"; // Importing Inter from the Google package
import "./globals.css";
import NavBar from "@/components/Navbar";

const inter = Inter({
  subsets: ["latin"], // Specify subsets as needed
  variable: "--font-inter", // Define a CSS variable for the font
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}